In [1]:
import torch

$b=-1,w=2$

$\hat{y}=-1+2x$


In [2]:
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(-1.0, requires_grad=True)

In [3]:
def forward(x):
    yhat = w*x + b
    return yhat

$\hat{y}=-1+2x$

$\hat{y}=-1+2(1)$

In [4]:
x = torch.tensor([[1.0]])
yhat = forward(x)
print("The prediction: ", yhat)

The prediction:  tensor([[1.]], grad_fn=<AddBackward0>)


<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.1.2.png" width="500" alt="Linear Regression Multiple Input Samples">



In [9]:
# Make the prediction of y = 2x - 1 at x = [1, 2]
x = torch.tensor([[1.0], [2.0]])
print("The shape of x: ", x.shape)
yhat = forward(x)
print("The prediction: ", yhat)

The shape of x:  torch.Size([2, 1])
The prediction:  tensor([[1.],
        [3.]], grad_fn=<AddBackward0>)


In [8]:
x = torch.tensor([[1.0],[2.0], [3.0]])
yhat = forward(x)
yhat

tensor([[1.],
        [3.],
        [5.]], grad_fn=<AddBackward0>)

In [10]:
from torch.nn import Linear

In [11]:
torch.manual_seed(1)

In [12]:
lr = Linear(in_features=1 , out_features=1 ,bias=True)
list(lr.parameters()) # w,b

[Parameter containing:
 tensor([[0.5153]], requires_grad=True),
 Parameter containing:
 tensor([-0.4414], requires_grad=True)]

$b=-0.44, w=0.5153$

$\hat{y}=-0.44+0.5153x$


In [14]:
print("Python dict: ", lr.state_dict())
print("Keys: ", lr.state_dict().keys())
print("Values: ", lr.state_dict().values())

Python dict:  OrderedDict([('weight', tensor([[0.5153]])), ('bias', tensor([-0.4414]))])
Keys:  odict_keys(['weight', 'bias'])
Values:  odict_values([tensor([[0.5153]]), tensor([-0.4414])])


In [15]:
print(lr.weight)
print(lr.bias)

Parameter containing:
tensor([[0.5153]], requires_grad=True)
Parameter containing:
tensor([-0.4414], requires_grad=True)


In [23]:
# Make the prediction at x = [[1.0]]
x = torch.tensor([[1.0]], requires_grad=True)
yhat = lr(x)
yhat

tensor([[0.0739]], grad_fn=<AddmmBackward0>)

In [24]:
yhat.backward()
x.grad

tensor([[0.5153]])

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0110EN/notebook_images%20/chapter2/2.1.2vector_function.png" width="500" alt="Linear Class Sample with Multiple Inputs">

In [29]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
print(yhat)

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward0>)


In [30]:
x = torch.tensor([[1.0], [2.0], [3.0]])

yhat = lr(x)
yhat

tensor([[0.0739],
        [0.5891],
        [1.1044]], grad_fn=<AddmmBackward0>)

In [31]:
from torch import nn

In [33]:
class LR(nn.Module):
    def __init__(self, input_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        out = self.linear(x)
        return out

In [55]:
lr = LR(1,1)
print("The param: ", list(lr.parameters()))
lr.linear

The param:  [Parameter containing:
tensor([[-0.7201]], requires_grad=True), Parameter containing:
tensor([-0.6048], requires_grad=True)]


Linear(in_features=1, out_features=1, bias=True)

In [57]:
x = torch.tensor([[1.0]])
yhat = lr(x)
yhat

tensor([[-1.3249]], grad_fn=<AddmmBackward0>)

In [58]:
x = torch.tensor([[1.0], [2.0]])
yhat = lr(x)
yhat

tensor([[-1.3249],
        [-2.0450]], grad_fn=<AddmmBackward0>)

In [60]:
print("Dict: ", lr.state_dict())
print("Keys: ", lr.state_dict().keys())
print("Values: ", lr.state_dict().values())


Dict:  OrderedDict([('linear.weight', tensor([[-0.7201]])), ('linear.bias', tensor([-0.6048]))])
Keys:  odict_keys(['linear.weight', 'linear.bias'])
Values:  odict_values([tensor([[-0.7201]]), tensor([-0.6048])])


# Practice

In [65]:
class lr2(nn.Module):
    def __init__(self, input_size,output_size):
        super(lr2, self).__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        out = self.linear(x)
        return out
    
lr = lr2(1,1)
print(lr.linear)
    
x = torch.tensor([[0.1], [0.2], [0.3]])
yhat = lr(x)
yhat

Linear(in_features=1, out_features=1, bias=True)


tensor([[-0.9956],
        [-1.0509],
        [-1.1063]], grad_fn=<AddmmBackward0>)